version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: kinos
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    stdin_open: true
    tty: true
  caddy:
    build: caddy
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - web
      - db
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile